# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    unsignedPipelineResource: null
    unsignedArtifactName: null
    signedArtifactName: null

jobs:
    - job: ${{ parameters.signedArtifactName }}
      pool:
          vmImage: macOS-10.15
      variables:
          - group: mac-notarization-developerid-certificate-secrets
      steps:
          - template: ../../install-node-prerequisites.yaml

          - task: DownloadPipelineArtifact@2
            inputs:
                source: 'specific'
                runVersion: 'specific'
                project: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.projectID)
                pipeline: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.pipelineID)
                runId: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.runID)
                artifact: ${{ parameters.unsignedArtifactName }}
                path: '$(System.DefaultWorkingDirectory)/signing-in-progress/${{ parameters.signedArtifactName }}'

          - script: |
            echo "$(mac-notarization-developerid-certificate-identity)"
          displayName: trying something

          - template: sign-release-package.yaml
            parameters:
                filePattern: '*.dmg, *.zip'
                platform: mac
                signedArtifactName: ${{ parameters.signedArtifactName }}
                inlineSignParams: |
                    [
                        {
                            "keyCode": "CP-401337-Apple",
                            "operationSetCode": "MacAppDeveloperSign",
                            "parameters": [],
                            "toolName": "sign",
                            "toolVersion": "1.0"
                        }
                    ]

          # Get Cert

          # Put Cert into keychain

          # Run Codesign

          # - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
          #   displayName: 'ESRP signing installer'
          #   inputs:
          #       ConnectedServiceName: 'ESRP Code Signing'
          #       FolderPath: '$(System.DefaultWorkingDirectory)/signing-in-progress/${{ parameters.signedArtifactName }}/packed'
          #       Pattern: '*.dmg, *.zip'
          #       signConfigType: inlineSignParams
          #       inlineOperation: |
          #           [
          #               {
          #                   "keyCode": "CP-401337-Apple",
          #                   "operationSetCode": "MacAppDeveloperSign",
          #                   "parameters": [
          #                     {
          #                       "parameterName": "Hardening",
          #                       "parameterValue": "--options=runtime"
          #                     }
          #                   ],
          #                   "toolName": "sign",
          #                   "toolVersion": "1.0"
          #               }
          #           ]

          # - script: node ./pipeline/scripts/update-latest-yml.js signing-in-progress/${{ parameters.signedArtifactName }}/packed mac
          #   displayName: update electron-builder latest.yml after signing

          # - template: ../publish-packed-build-output.yaml
          #   parameters:
          #       packedOutputPath: '$(System.DefaultWorkingDirectory)/signing-in-progress/${{ parameters.signedArtifactName }}/packed'
          #       artifactName: ${{ parameters.signedArtifactName }}
